name = "plastdu"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SITE_URL = "https://plastdu.ro"
ADMIN_PASSWORD = "PlastDu#2026"
JWT_SECRET = "plastdu-jwt-secret-2026-xK9mP3qR"

[[kv_namespaces]]
binding = "PLASTDU_CONTENT"
id = "144e41df923a41e9abe1827446801e19"

[[r2_buckets]]
binding = "PLASTDU_IMAGES"
bucket_name = "plastdu-images"
